$(document).ready(function() {
  $('#jmap').jmap({
      width: '100%',
      height: '450px',
      lineColor: '#ea55040a',
      lineWidth: 2,
      showTextShadow: true,
      backgroundColor: 'white',
      backgroundRadius: '0.5rem',
      backgroundPadding: '0.5rem',
      dividerColor: '#EFE4A6',
      showPrefectureName: true,
      showRoundedPrefecture: true,
      prefectureNameType: 'full',
      prefectureBackgroundColor: '#e94709',
      prefectureBackgroundHoverColor: '#ea55040a',
      prefectureLineColor: '#EFE4A6',
      prefectureLineHoverColor: '#ffffff',
      prefectureLineWidth: '2px',
      prefectureLineGap: '0px',
      prefectureInnerLineWidth: '1px',
      prefectureInnerLineColor: '#EFE4A6',
      prefectureInnerLineType: 'outset',
      prefectureRadius: '15px',
      prefectureLineY: '2px',
      prefectureLineX: '2px',
      fontSize: '0.6rem',
      fontColor: '#fff',
      backgroundColor: '#ea55040a',
      onSelect: function(e, data) {
        window.location.href = `prefectures/${data.option.code}`;
      },
      areas: [
        {code: 1,name: "北海道",number: 5320},
        {code: 2,name: "青森",number: 1278},
        {code: 3,name: "岩手",number: 1255},
        {code: 4,name: "宮城",number: 2323},
        {code: 5,name: "秋田",number: 996},
        {code: 6,name: "山形",number: 1102},
        {code: 7,name: "福島",number: 1882},
        {code: 8,name: "茨城",number: 2892},
        {code: 9,name: "栃木",number: 1957},
        {code: 10,name: "群馬",number: 1960},
        {code: 11,name: "埼玉",number: 7310},
        {code: 12,name: "千葉",number: 6246},
        {code: 13,name: "東京",number: 13724},
        {code: 14,name: "神奈川",number: 9159},
        {code: 15,name: "新潟",number: 2267},
        {code: 16,name: "富山",number: 1056},
        {code: 17,name: "石川",number: 1147},
        {code: 18,name: "福井",number: 779},
        {code: 19,name: "山梨",number: 823},
        {code: 20,name: "長野",number: 2076},
        {code: 21,name: "岐阜",number: 2008},
        {code: 22,name: "静岡",number: 3675},
        {code: 23,name: "愛知",number: 7525},
        {code: 24,name: "三重",number: 1800},
        {code: 25,name: "滋賀",number: 1413},
        {code: 26,name: "京都",number: 2599},
        {code: 27,name: "大阪",number: 8823},
        {code: 28,name: "兵庫",number: 5503},
        {code: 29,name: "奈良",number: 1348},
        {code: 30,name: "和歌山",number: 945},
        {code: 31,name: "鳥取",number: 565},
        {code: 32,name: "島根",number: 685},
        {code: 33,name: "岡山",number: 1907},
        {code: 34,name: "広島",number: 2829},
        {code: 35,name: "山口",number: 1383},
        {code: 36,name: "徳島",number: 743},
        {code: 37,name: "香川",number: 967},
        {code: 38,name: "愛媛",number: 1364},
        {code: 39,name: "高知",number: 714},
        {code: 40,name: "福岡",number: 5107},
        {code: 41,name: "佐賀",number: 824},
        {code: 42,name: "長崎",number: 1354},
        {code: 43,name: "熊本",number: 1765},
        {code: 44,name: "大分",number: 1152},
        {code: 45,name: "宮崎",number: 1089},
        {code: 46,name: "鹿児島",number: 1626},
        {code: 47,name: "沖縄",number: 1443}
        ]
  });
});